### ISSUE TITLE
issues installing capybara-webkit

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/rails-simple-search#2]
While running bundle install on this lab, capybara-webkit failed to install with this error:

``` bash
Installing capybara-webkit 1.4.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/iancandy/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20151026-39749-1tcwtps.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

I was able to install it by following the instructions here - https://github.com/thoughtbot/capybara-webkit/issues/813

I'm not sure if this will be an issue for others or not. If so, we should include these instructions in the README. If not, we can close this issue.

**Comment by vinnyalfieri** [comment]
I was unable to reproduce this issue on my machine.

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue is being closed now as stale. If the issue is encountered again, please first consult the [Learn Help Center](http://help.learn.co/) and the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature. If neither of those options resolves the problem and you still feel that this is an issue with the curriculum, please reopen this issue and provide as much detail as possible:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂
